spring.application.name=smart-sejong
spring.jpa.open-in-view=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console disabled
spring.h2.console.enabled=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-validity=3600000
jwt.refresh-token-validity=604800000
